<?php
/**
 * Category view template
 *
 * @var $block \Bss\Fresher\Block\Fresher
 */
?>
<h1><?= $escaper->escapeHtml($block->getHelloworldData()); ?></h1>
<form id="fresher-form">
    <label for="name">Name:</label>
    <input type="text" name="name" id="name" required>

    <label for="telephone">Telephone:</label>
    <input type="tel" name="telephone" id="telephone" required>

    <label for="dob">Date of Birth:</label>
    <input type="date" name="dob" id="dob" required>

    <label for="message">Message:</label>
    <textarea name="message" id="message"></textarea>

    <button id="submitBtn" >Submit</button>
</form>
<script type="text/x-magento-init">
    {
        "#fresher-form": {
            "customFormHandler": {}
        }
    }
</script>
